apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -green
commonLabels:
  version: green
images:
  - name: nginx
    newTag: "1.20"  # Version plus r√©cente